### ISSUE TITLE
Problems with ignoring multiline merge commit messages

### ISSUE THREAD

**Issue by matecode** [hyiso/commitlint#20]
I have multiline merge commit messages from my IDE (IntelliJ), and i cannot convince commitlint_cli to ignore them. This is my commit msg:
```
Merge branch 'develop' into feature/xyz

# Conflicts:
#	xyz.yaml
```
And here is my commitlint.yaml
```
# Inherit configuration of a package
include: package:commitlint_cli/commitlint.yaml

# Custom rules
rules:
  references-empty:
    - 1
    - never
  scope-case:
    - 2
    - always
    - lower-case
  scope-enum:
    - 1
    - always
    - - app
      - core
# Whether commitlint uses the default ignore rules like merge commits
defaultIgnores: true
# Pattern that matches commit message if commitlint should ignore the given message.
ignores:
  - r'Merge branch.*(?:\r?\n.*)*'
  - r'Merge branch[\s\S]*'
```
But as soon as the commit message is "multiline" commitlint_cli fails:
```
⧗  input: Merge branch 'develop' into feature/xyz

# Conflicts:
#       xyz.yaml


✖  type must not be empty type-empty
⚠  references must not be empty references-empty

✖  found 1 error(s), 1 warning(s)
```

I appreciate any help!
