### ISSUE TITLE
bug: the parser `issuePrefixes` still can't pass the `references-empty` rule test

### ISSUE THREAD

**Issue by KeidsID** [hyiso/commitlint#23]
## Describe Your Issue?

I've seen the #22 PR. But the parser feature still can't pass the `references-empty` rule test.

## Steps To Reproduce

1. Follow the [commintlint_cli setup documentation](https://hyiso.github.io/commitlint/#/guides-setup) on your dart/flutter project.

2. Make sure to use `commintlint_cli` v0.8.0 on `pubspec.yaml`.

   ```yml
   dev_dependencies:
     commitlint_cli: ^0.8.0
   ```

3. Create the `commitlint.yaml` file on project root with the following content:

   ```yml
   # https://github.com/hyiso/commitlint/blob/main/lib/commitlint.yaml
   include: package:commitlint_cli/commitlint.yaml

   # https://github.com/hyiso/commitlint/pull/22
   parser:
     issuePrefixes:
       - "sv-"

   # https://hyiso.github.io/commitlint/#/references-rules
   rules:
     type-enum:
       - 2
       - always
       - - build
         - chore
         - docs
         - feat
         - fix
         - refactor
         - revert
         - style
         - test
     scope-enum:
       - 2
       - always
       - - domain
         - infrastructures
         - use_cases
         - interfaces
         - lib
         - root
     references-empty:
       - 2
       - never
   ```

4. Try to commit with the following message:

   ```bash
   $ feat: add tv shows service sv-25
   $ fix: fix unresponsive movies page sv-250
   $ fix(root): fix commitlint config sv-1
   ```

## Expected Result

The commitlint should pass the `references-empty` rule test.

## Actual Result

The commitlint fails the `references-empty` rule test.

```bash
⧗  input: fix(root): fix commitlint config sv-1


✖  references must not be empty references-empty

✖  found 1 error(s), 0 warning(s)
```

## Additional Screenshots/Videos

https://github.com/user-attachments/assets/a2570fb2-e756-461c-9d16-aeb5be3d3f10

[Repo link](https://github.com/KeidsID/shows_vault)

## What OS are you using?

Windows 11 Home Single Language

## What version of Dart/Flutter are you using?

Flutter v3.24.0 (stable) Windows.
