### ISSUE TITLE
How to use it in Github Actions?

### ISSUE THREAD

**Issue by provokateurin** [hyiso/commitlint#7]
Hi, I'm trying to use commitlint in Github Actions to validate commit messages in the CI. For some reason I can't get it to fail when it should. The current workflow is at https://github.com/provokateurin/nextcloud-neon/pull/468/commits/a32ce684c64b9a1a1fd082ed2f32d274f454696f. I was able to get it working locally with https://github.com/nektos/act when using `--from=main --to=@`, but that also didn't work on Github Actions. Can someone help me get this working? I'm not sure if the workflow is the problem or if there is a bug in this tool.

**Comment by hyiso** [comment]
You can see the configuration in this repo https://github.com/hyiso/commitlint/blob/main/.github/workflows/pr_title.yml

**Comment by provokateurin** [comment]
That only validates the PR title but I can't get it working with the commit range of the PR

**Comment by hyiso** [comment]
I've added a Github Action in this repo and created a PR  to test it https://github.com/hyiso/commitlint/pull/8.

From [The Action Running Log](https://github.com/hyiso/commitlint/actions/runs/5560791875/jobs/10158024659?pr=8), the problem happened during getting commit messages in Github Action Runner, which seems to be not related to this package:

```bash
commitlint:read - from = main, to = feature/validate-pr-commit, edit = null
commitlint:read - git log --format=%B main..feature/validate-pr-commit
commitlint:read - stdout = 
commitlint:read - stderr = fatal: ambiguous argument 'main..feature/validate-pr-commit': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by provokateurin** [comment]
Thanks for the investigation. Can we still try to fix it here? I already tried things like fetching the whole repo or pulling the main branch etc.

**Comment by provokateurin** [comment]
Can you try
```yaml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

**Comment by hyiso** [comment]
After several tries, the following configuration works finally:
```yaml
uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
...
dart run commitlint_cli --from="origin/${{ github.base_ref }}" --to="${{ github.head_ref }}"
```
You can see the log https://github.com/hyiso/commitlint/actions/runs/5560955537/jobs/10158300171?pr=8

The important parts are checkout with `ref` and `--from` with `origin/` prefix
